[package]
name = "passeri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
bytes = "1.5.0"
midir = "0.9.1"
tokio = { version = "1", features = ["full"] }
